/*
    MajorVersion.MinorVersion.BuildNumber.RevisionNumber(QFE)

    QFE = Quick Fix Engineering

    Example 1.0.1.1 means:

    MajorVersion        = 1
    MinorVersion        = 0
    BuildNumber         = 1
    RevisionNumber(QFE) = 1

*/


/* COMMON FOR ALL MODULES */
#define  THIN_COMMON_COMPANYNAME      "thinBasic\0"
#define  THIN_COMMON_LEGALCOPYRIGHT   "(c) 2004-2016 thinBasic.com\0"
#define  THIN_COMMON_COMMENT          "Support site: http://www.thinbasic.com\0"


/* Force the same version number to all modules */
#define  FORCE_VERSION_EQUAL_FOR_ALL_MODULES             1
#include "TBVersion.h"

/* THINBASIC_ADO.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_ADO_VERSIONMAJOR       THIN_VERSIONMAJOR
#define  THINBASIC_ADO_VERSIONMINOR       THIN_VERSIONMINOR
#define  THINBASIC_ADO_VERSIONBUILD       THIN_VERSIONBUILD
#define  THINBASIC_ADO_VERSIONREVISION    THIN_VERSIONREVISION
#define  THINBASIC_ADO_VERSIONLITERAL     THIN_VERSIONLITERAL
#else
#define  THINBASIC_ADO_VERSIONMAJOR       1
#define  THINBASIC_ADO_VERSIONMINOR       0
#define  THINBASIC_ADO_VERSIONBUILD       1
#define  THINBASIC_ADO_VERSIONREVISION    1
#define  THINBASIC_ADO_VERSIONLITERAL     "1.0.1.1\0"
#endif
#define  THINBASIC_ADO_INTERNALNAME       "thinBasic_ADO\0"
#define  THINBASIC_ADO_FILEDESCRIPTION    "thinBasic ActiveX Data Objects Library\0"
#define  THINBASIC_ADO_ORIGINALFILENAME   "thinBasic_ADO.dll\0"
#define  THINBASIC_ADO_PRODUCTNAME        "thinBasic ADO\0"

/* THINBASIC_ADODB.Dll */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_ADODB_VERSIONMAJOR       THIN_VERSIONMAJOR
#define  THINBASIC_ADODB_VERSIONMINOR       THIN_VERSIONMINOR
#define  THINBASIC_ADODB_VERSIONBUILD       THIN_VERSIONBUILD
#define  THINBASIC_ADODB_VERSIONREVISION    THIN_VERSIONREVISION
#define  THINBASIC_ADODB_VERSIONLITERAL     THIN_VERSIONLITERAL
#else
#define  THINBASIC_ADODB_VERSIONMAJOR       1
#define  THINBASIC_ADODB_VERSIONMINOR       0
#define  THINBASIC_ADODB_VERSIONBUILD       1
#define  THINBASIC_ADODB_VERSIONREVISION    1
#define  THINBASIC_ADODB_VERSIONLITERAL     "1.0.1.1\0"
#endif
#define  THINBASIC_ADODB_INTERNALNAME       "thinBasic_ADODB\0"
#define  THINBASIC_ADODB_FILEDESCRIPTION    "thinBasic ADODB Library\0"
#define  THINBASIC_ADODB_ORIGINALFILENAME   "thinBasic_ADODB.dll\0"
#define  THINBASIC_ADODB_PRODUCTNAME        "thinBasic ADODB\0"

/* THINBASIC_CGI.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_CGI_VERSIONMAJOR       THIN_VERSIONMAJOR
#define  THINBASIC_CGI_VERSIONMINOR       THIN_VERSIONMINOR
#define  THINBASIC_CGI_VERSIONBUILD       THIN_VERSIONBUILD
#define  THINBASIC_CGI_VERSIONREVISION    THIN_VERSIONREVISION
#define  THINBASIC_CGI_VERSIONLITERAL     THIN_VERSIONLITERAL
#else
#define  THINBASIC_CGI_VERSIONMAJOR       1
#define  THINBASIC_CGI_VERSIONMINOR       0
#define  THINBASIC_CGI_VERSIONBUILD       1
#define  THINBASIC_CGI_VERSIONREVISION    1
#define  THINBASIC_CGI_VERSIONLITERAL     "1.0.1.1\0"
#endif
#define  THINBASIC_CGI_INTERNALNAME       "thinBasic_CGI\0"
#define  THINBASIC_CGI_FILEDESCRIPTION    "thinBasic Common Gateway Interface Library\0"
#define  THINBASIC_CGI_ORIGINALFILENAME   "thinBasic_CGI.dll\0"
#define  THINBASIC_CGI_PRODUCTNAME        "thinBasic CGI\0"

/* THINBASIC_CONSOLE.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_CONSOLE_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_CONSOLE_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_CONSOLE_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_CONSOLE_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_CONSOLE_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_CONSOLE_VERSIONMAJOR        1
#define  THINBASIC_CONSOLE_VERSIONMINOR        0
#define  THINBASIC_CONSOLE_VERSIONBUILD        1
#define  THINBASIC_CONSOLE_VERSIONREVISION     1
#define  THINBASIC_CONSOLE_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_CONSOLE_INTERNALNAME        "thinBasic_Console\0"
#define  THINBASIC_CONSOLE_FILEDESCRIPTION     "thinBasic Console Library\0"
#define  THINBASIC_CONSOLE_ORIGINALFILENAME    "thinBasic_Console.dll\0"
#define  THINBASIC_CONSOLE_PRODUCTNAME         "thinBasic Console\0"

/* THINBASIC_CONSOLE9x.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_CONSOLE9x_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_CONSOLE9x_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_CONSOLE9x_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_CONSOLE9x_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_CONSOLE9x_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_CONSOLE9x_VERSIONMAJOR        1
#define  THINBASIC_CONSOLE9x_VERSIONMINOR        0
#define  THINBASIC_CONSOLE9x_VERSIONBUILD        1
#define  THINBASIC_CONSOLE9x_VERSIONREVISION     1
#define  THINBASIC_CONSOLE9x_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_CONSOLE9x_INTERNALNAME        "thinBasic_Console9x\0"
#define  THINBASIC_CONSOLE9x_FILEDESCRIPTION     "thinBasic Console Library for Windows 95/98/ME\0"
#define  THINBASIC_CONSOLE9x_ORIGINALFILENAME    "thinBasic_Console9x.dll\0"
#define  THINBASIC_CONSOLE9x_PRODUCTNAME         "thinBasic Console for Windows 95/98/ME\0"

/* THINBASIC_CRYPTO.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_CRYPTO_VERSIONMAJOR         THIN_VERSIONMAJOR
#define  THINBASIC_CRYPTO_VERSIONMINOR         THIN_VERSIONMINOR
#define  THINBASIC_CRYPTO_VERSIONBUILD         THIN_VERSIONBUILD
#define  THINBASIC_CRYPTO_VERSIONREVISION      THIN_VERSIONREVISION
#define  THINBASIC_CRYPTO_VERSIONLITERAL       THIN_VERSIONLITERAL
#else
#define  THINBASIC_CRYPTO_VERSIONMAJOR         1
#define  THINBASIC_CRYPTO_VERSIONMINOR         0
#define  THINBASIC_CRYPTO_VERSIONBUILD         1
#define  THINBASIC_CRYPTO_VERSIONREVISION      1
#define  THINBASIC_CRYPTO_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_CRYPTO_INTERNALNAME         "thinBasic_Crypto\0"
#define  THINBASIC_CRYPTO_FILEDESCRIPTION      "thinBasic Cryptography Library\0"
#define  THINBASIC_CRYPTO_ORIGINALFILENAME     "thinBasic_Crypto.dll\0"
#define  THINBASIC_CRYPTO_PRODUCTNAME          "thinBasic Cryptography\0"

/* THINBASIC_DICTIONARY.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_DICTIONARY_VERSIONMAJOR       THIN_VERSIONMAJOR
#define  THINBASIC_DICTIONARY_VERSIONMINOR       THIN_VERSIONMINOR
#define  THINBASIC_DICTIONARY_VERSIONBUILD       THIN_VERSIONBUILD
#define  THINBASIC_DICTIONARY_VERSIONREVISION    THIN_VERSIONREVISION
#define  THINBASIC_DICTIONARY_VERSIONLITERAL     THIN_VERSIONLITERAL
#else
#define  THINBASIC_DICTIONARY_VERSIONMAJOR       1
#define  THINBASIC_DICTIONARY_VERSIONMINOR       0
#define  THINBASIC_DICTIONARY_VERSIONBUILD       1
#define  THINBASIC_DICTIONARY_VERSIONREVISION    1
#define  THINBASIC_DICTIONARY_VERSIONLITERAL     "1.0.1.1\0"
#endif
#define  THINBASIC_DICTIONARY_INTERNALNAME       "thinBasic_Dictionary\0"
#define  THINBASIC_DICTIONARY_FILEDESCRIPTION    "thinBasic Dictionary Library\0"
#define  THINBASIC_DICTIONARY_ORIGINALFILENAME   "thinBasic_Dictionary.dll\0"
#define  THINBASIC_DICTIONARY_PRODUCTNAME        "thinBasic Dictionary\0"

/* THINBASIC_DT.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_DT_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_DT_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_DT_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_DT_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_DT_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_DT_VERSIONMAJOR             1
#define  THINBASIC_DT_VERSIONMINOR                 0
#define  THINBASIC_DT_VERSIONBUILD                 1
#define  THINBASIC_DT_VERSIONREVISION              1
#define  THINBASIC_DT_VERSIONLITERAL               "1.0.1.1\0"
#endif
#define  THINBASIC_DT_INTERNALNAME             "thinBasic_DT\0"
#define  THINBASIC_DT_FILEDESCRIPTION          "thinBasic Date and Time Library\0"
#define  THINBASIC_DT_ORIGINALFILENAME         "thinBasic_DT.dll\0"
#define  THINBASIC_DT_PRODUCTNAME              "thinBasic Date and Time\0"

/* THINBASIC_BIFF.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_BIFF_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_BIFF_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_BIFF_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_BIFF_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_BIFF_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_BIFF_VERSIONMAJOR             1
#define  THINBASIC_BIFF_VERSIONMINOR          0
#define  THINBASIC_BIFF_VERSIONBUILD          1
#define  THINBASIC_BIFF_VERSIONREVISION       1
#define  THINBASIC_BIFF_VERSIONLITERAL        "1.0.1.1\0"
#endif
#define  THINBASIC_BIFF_INTERNALNAME              "thinBasic_Biff\0"
#define  THINBASIC_BIFF_FILEDESCRIPTION       "thinBasic Biff Library\0"
#define  THINBASIC_BIFF_ORIGINALFILENAME         "thinBasic_Biff.dll\0"
#define  THINBASIC_BIFF_PRODUCTNAME              "thinBasic Biff\0"

/* THINBASIC_CJSon.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_CJSON_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_CJSON_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_CJSON_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_CJSON_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_CJSON_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_CJSON_VERSIONMAJOR             1
#define  THINBASIC_CJSON_VERSIONMINOR                 0
#define  THINBASIC_CJSON_VERSIONBUILD         1
#define  THINBASIC_CJSON_VERSIONREVISION      1
#define  THINBASIC_CJSON_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_CJSON_INTERNALNAME             "thinBasic_CJSon\0"
#define  THINBASIC_CJSON_FILEDESCRIPTION          "thinBasic JSon Library\0"
#define  THINBASIC_CJSON_ORIGINALFILENAME         "thinBasic_CJSon.dll\0"
#define  THINBASIC_CJSON_PRODUCTNAME              "thinBasic JSon Library\0"



/* THINBASIC_COM.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_COM_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_COM_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_COM_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_COM_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_COM_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_COM_VERSIONMAJOR             1
#define  THINBASIC_COM_VERSIONMINOR                 0
#define  THINBASIC_COM_VERSIONBUILD         1
#define  THINBASIC_COM_VERSIONREVISION      1
#define  THINBASIC_COM_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_COM_INTERNALNAME             "thinBasic_COM\0"
#define  THINBASIC_COM_FILEDESCRIPTION              "thinBasic COM (Components Object Model) File Library\0"
#define  THINBASIC_COM_ORIGINALFILENAME         "thinBasic_COM.dll\0"
#define  THINBASIC_COM_PRODUCTNAME              "thinBasic Components Object Model File Library\0"

/* THINBASIC_COMM.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_COMM_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_COMM_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_COMM_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_COMM_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_COMM_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_COMM_VERSIONMAJOR             1
#define  THINBASIC_COMM_VERSIONMINOR                0
#define  THINBASIC_COMM_VERSIONBUILD        1
#define  THINBASIC_COMM_VERSIONREVISION     1
#define  THINBASIC_COMM_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_COMM_INTERNALNAME            "thinBasic_COMM\0"
#define  THINBASIC_COMM_FILEDESCRIPTION             "thinBasic COMM (Serial Communication) File Library\0"
#define  THINBASIC_COMM_ORIGINALFILENAME         "thinBasic_COMM.dll\0"
#define  THINBASIC_COMM_PRODUCTNAME              "thinBasic Serial Communication File Library\0"

/* THINBASIC_DATA.Dll */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_DATASTRUCTURES_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_DATASTRUCTURES_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_DATASTRUCTURES_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_DATASTRUCTURES_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_DATASTRUCTURES_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_DATASTRUCTURES_VERSIONMAJOR             1
#define  THINBASIC_DATASTRUCTURES_VERSIONMINOR                0
#define  THINBASIC_DATASTRUCTURES_VERSIONBUILD        1
#define  THINBASIC_DATASTRUCTURES_VERSIONREVISION     1
#define  THINBASIC_DATASTRUCTURES_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_DATASTRUCTURES_INTERNALNAME            "thinBasic_Data\0"
#define  THINBASIC_DATASTRUCTURES_FILEDESCRIPTION         "thinBasic Data (Data Structure) Library\0"
#define  THINBASIC_DATASTRUCTURES_ORIGINALFILENAME        "thinBasic_Data.dll\0"
#define  THINBASIC_DATASTRUCTURES_PRODUCTNAME             "thinBasic Data Structure Library\0"

/* THINBASIC_EVAL.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_EVAL_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_EVAL_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_EVAL_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_EVAL_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_EVAL_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_EVAL_VERSIONMAJOR             1
#define  THINBASIC_EVAL_VERSIONMINOR                0
#define  THINBASIC_EVAL_VERSIONBUILD        1
#define  THINBASIC_EVAL_VERSIONREVISION     1
#define  THINBASIC_EVAL_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_EVAL_INTERNALNAME            "thinBasic_Eval\0"
#define  THINBASIC_EVAL_FILEDESCRIPTION             "thinBasic Eval Library\0"
#define  THINBASIC_EVAL_ORIGINALFILENAME         "thinBasic_Eval.dll\0"
#define  THINBASIC_EVAL_PRODUCTNAME              "thinBasic Eval\0"

/* THINBASIC_FILE.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_FILE_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_FILE_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_FILE_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_FILE_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_FILE_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_FILE_VERSIONMAJOR             1
#define  THINBASIC_FILE_VERSIONMINOR         0
#define  THINBASIC_FILE_VERSIONBUILD         1
#define  THINBASIC_FILE_VERSIONREVISION      1
#define  THINBASIC_FILE_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_FILE_INTERNALNAME             "thinBasic_File\0"
#define  THINBASIC_FILE_FILEDESCRIPTION      "thinBasic File Support Library\0"
#define  THINBASIC_FILE_ORIGINALFILENAME         "thinBasic_File.dll\0"
#define  THINBASIC_FILE_PRODUCTNAME              "thinBasic File\0"

/* THINBASIC_FTP.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_FTP_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_FTP_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_FTP_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_FTP_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_FTP_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_FTP_VERSIONMAJOR             1
#define  THINBASIC_FTP_VERSIONMINOR                 0
#define  THINBASIC_FTP_VERSIONBUILD         1
#define  THINBASIC_FTP_VERSIONREVISION      1
#define  THINBASIC_FTP_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_FTP_INTERNALNAME             "thinBasic_FTP\0"
#define  THINBASIC_FTP_FILEDESCRIPTION              "thinBasic File Transfer Protocol Library\0"
#define  THINBASIC_FTP_ORIGINALFILENAME         "thinBasic_FTP.dll\0"
#define  THINBASIC_FTP_PRODUCTNAME              "thinBasic File Transfer Protocol\0"

/* THINBASIC_GDIPLUS.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_GDIPLUS_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_GDIPLUS_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_GDIPLUS_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_GDIPLUS_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_GDIPLUS_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_GDIPLUS_VERSIONMAJOR             1
#define  THINBASIC_GDIPLUS_VERSIONMINOR         0
#define  THINBASIC_GDIPLUS_VERSIONBUILD         1
#define  THINBASIC_GDIPLUS_VERSIONREVISION      1
#define  THINBASIC_GDIPLUS_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_GDIPLUS_INTERNALNAME             "thinBasic_GDIPLUS\0"
#define  THINBASIC_GDIPLUS_FILEDESCRIPTION      "thinBasic GDIPLUS Library\0"
#define  THINBASIC_GDIPLUS_ORIGINALFILENAME         "thinBasic_GDIPLUS.dll\0"
#define  THINBASIC_GDIPLUS_PRODUCTNAME              "thinBasic GDIPLUS\0"

/* THINIMG.Dll */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINIMG_VERSIONMAJOR              THIN_VERSIONMAJOR
#define  THINIMG_VERSIONMINOR              THIN_VERSIONMINOR
#define  THINIMG_VERSIONBUILD              THIN_VERSIONBUILD
#define  THINIMG_VERSIONREVISION           THIN_VERSIONREVISION
#define  THINIMG_VERSIONLITERAL            THIN_VERSIONLITERAL
#else
#define  THINIMG_VERSIONMAJOR              1
#define  THINIMG_VERSIONMINOR              0
#define  THINIMG_VERSIONBUILD              1
#define  THINIMG_VERSIONREVISION           1
#define  THINIMG_VERSIONLITERAL            "1.0.1.1\0"
#endif
#define  THINIMG_INTERNALNAME              "ThinImg\0"
#define  THINIMG_FILEDESCRIPTION           "thinBasic Image Library\0"
#define  THINIMG_ORIGINALFILENAME          "ThinImg.dll\0"
#define  THINIMG_PRODUCTNAME               "thinBasic Image Library\0"

/* THINBASIC_ICOMPLEX.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_ICOMPLEX_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_ICOMPLEX_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_ICOMPLEX_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_ICOMPLEX_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_ICOMPLEX_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_ICOMPLEX_VERSIONMAJOR             1
#define  THINBASIC_ICOMPLEX_VERSIONMINOR             0
#define  THINBASIC_ICOMPLEX_VERSIONBUILD         1
#define  THINBASIC_ICOMPLEX_VERSIONREVISION      1
#define  THINBASIC_ICOMPLEX_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_ICOMPLEX_INTERNALNAME         "thinBasic_iComplex\0"
#define  THINBASIC_ICOMPLEX_FILEDESCRIPTION      "thinBasic Complex Numbers Library\0"
#define  THINBASIC_ICOMPLEX_ORIGINALFILENAME     "thinBasic_iComplex.dll\0"
#define  THINBASIC_ICOMPLEX_PRODUCTNAME          "thinBasic Complex Numbers\0"


/* THINBASIC_INET.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_INET_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_INET_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_INET_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_INET_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_INET_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_INET_VERSIONMAJOR             1
#define  THINBASIC_INET_VERSIONMINOR             0
#define  THINBASIC_INET_VERSIONBUILD         1
#define  THINBASIC_INET_VERSIONREVISION      1
#define  THINBASIC_INET_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_INET_INTERNALNAME             "thinBasic_INet\0"
#define  THINBASIC_INET_FILEDESCRIPTION      "thinBasic Internet Library\0"
#define  THINBASIC_INET_ORIGINALFILENAME         "thinBasic_INet.dll\0"
#define  THINBASIC_INET_PRODUCTNAME              "thinBasic Internet\0"

/* THINBASIC_INI.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_INI_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_INI_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_INI_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_INI_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_INI_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_INI_VERSIONMAJOR             1
#define  THINBASIC_INI_VERSIONMINOR                 0
#define  THINBASIC_INI_VERSIONBUILD         1
#define  THINBASIC_INI_VERSIONREVISION      1
#define  THINBASIC_INI_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_INI_INTERNALNAME             "thinBasic_INI\0"
#define  THINBASIC_INI_FILEDESCRIPTION              "thinBasic INI File Library\0"
#define  THINBASIC_INI_ORIGINALFILENAME         "thinBasic_INI.dll\0"
#define  THINBASIC_INI_PRODUCTNAME              "thinBasic INI File\0"

/* THINBASIC_LL.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_LL_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_LL_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_LL_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_LL_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_LL_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_LL_VERSIONMAJOR             1
#define  THINBASIC_LL_VERSIONMINOR             0
#define  THINBASIC_LL_VERSIONBUILD             1
#define  THINBASIC_LL_VERSIONREVISION              1
#define  THINBASIC_LL_VERSIONLITERAL               "1.0.1.1\0"
#endif
#define  THINBASIC_LL_INTERNALNAME             "thinBasic_LL\0"
#define  THINBASIC_LL_FILEDESCRIPTION          "thinBasic Linked List Library\0"
#define  THINBASIC_LL_ORIGINALFILENAME         "thinBasic_LL.dll\0"
#define  THINBASIC_LL_PRODUCTNAME              "thinBasic Linked List\0"

/* THINBASIC_MATH.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_MATH_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_MATH_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_MATH_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_MATH_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_MATH_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_MATH_VERSIONMAJOR            1
#define  THINBASIC_MATH_VERSIONMINOR            0
#define  THINBASIC_MATH_VERSIONBUILD            1
#define  THINBASIC_MATH_VERSIONREVISION         1
#define  THINBASIC_MATH_VERSIONLITERAL          "1.0.1.1\0"
#endif
#define  THINBASIC_MATH_INTERNALNAME           "thinBasic_Math\0"
#define  THINBASIC_MATH_FILEDESCRIPTION       "thinBasic Math Library\0"
#define  THINBASIC_MATH_ORIGINALFILENAME       "thinBasic_Math.dll\0"
#define  THINBASIC_MATH_PRODUCTNAME            "thinBasic Math\0"


/* THINBASIC_WINMM.DLL */
#define  THINBASIC_WINMM_VERSIONMAJOR		THIN_VERSIONMAJOR
#define  THINBASIC_WINMM_VERSIONMINOR		THIN_VERSIONMINOR
#define  THINBASIC_WINMM_VERSIONBUILD		THIN_VERSIONBUILD
#define  THINBASIC_WINMM_VERSIONREVISION	THIN_VERSIONREVISION
#define  THINBASIC_WINMM_VERSIONLITERAL		THIN_VERSIONLITERAL

#define  THINBASIC_WINMM_INTERNALNAME		"thinBasic_WinMM\0"
#define  THINBASIC_WINMM_FILEDESCRIPTION	"thinBasic Multimedia Library\0"
#define  THINBASIC_WINMM_ORIGINALFILENAME	"thinBasic_WinMM.dll\0"
#define  THINBASIC_WINMM_PRODUCTNAME		"thinBasic Multimedia Library\0"






/* THINBASIC_MSXML2.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_MSXML2_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_MSXML2_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_MSXML2_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_MSXML2_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_MSXML2_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_MSXML2_VERSIONMAJOR             1
#define  THINBASIC_MSXML2_VERSIONMINOR             0
#define  THINBASIC_MSXML2_VERSIONBUILD             1
#define  THINBASIC_MSXML2_VERSIONREVISION              1
#define  THINBASIC_MSXML2_VERSIONLITERAL               "1.0.1.1\0"
#endif
#define  THINBASIC_MSXML2_INTERNALNAME             "thinBasic_MSXML2\0"
#define  THINBASIC_MSXML2_FILEDESCRIPTION          "thinBasic MSXML2 Library\0"
#define  THINBASIC_MSXML2_ORIGINALFILENAME         "thinBasic_MSXML2.dll\0"
#define  THINBASIC_MSXML2_PRODUCTNAME              "thinBasic MSXML2\0"

/* THINBASIC_ODBC.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_ODBC_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_ODBC_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_ODBC_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_ODBC_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_ODBC_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_ODBC_VERSIONMAJOR             1
#define  THINBASIC_ODBC_VERSIONMINOR             0
#define  THINBASIC_ODBC_VERSIONBUILD             1
#define  THINBASIC_ODBC_VERSIONREVISION      1
#define  THINBASIC_ODBC_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_ODBC_INTERNALNAME             "thinBasic_ODBC\0"
#define  THINBASIC_ODBC_FILEDESCRIPTION      "thinBasic Open Database Connectivity Library\0"
#define  THINBASIC_ODBC_ORIGINALFILENAME         "thinBasic_ODBC.dll\0"
#define  THINBASIC_ODBC_PRODUCTNAME              "thinBasic Open Database Connectivity\0"

/* THINBASIC_ONLINESCORES.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_ONLINESCORES_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_ONLINESCORES_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_ONLINESCORES_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_ONLINESCORES_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_ONLINESCORES_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_ONLINESCORES_VERSIONMAJOR             1
#define  THINBASIC_ONLINESCORES_VERSIONMINOR             0
#define  THINBASIC_ONLINESCORES_VERSIONBUILD         1
#define  THINBASIC_ONLINESCORES_VERSIONREVISION      1
#define  THINBASIC_ONLINESCORES_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_ONLINESCORES_INTERNALNAME             "thinBasic_OnLineScores\0"
#define  THINBASIC_ONLINESCORES_FILEDESCRIPTION      "thinBasic OnLineScores System Library\0"
#define  THINBASIC_ONLINESCORES_ORIGINALFILENAME         "thinBasic_OnLineScores.dll\0"
#define  THINBASIC_ONLINESCORES_PRODUCTNAME              "thinBasic OnLineScores system\0"

/* THINBASIC_OS.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_OS_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_OS_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_OS_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_OS_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_OS_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_OS_VERSIONMAJOR             1
#define  THINBASIC_OS_VERSIONMINOR             0
#define  THINBASIC_OS_VERSIONBUILD             1
#define  THINBASIC_OS_VERSIONREVISION              1
#define  THINBASIC_OS_VERSIONLITERAL               "1.0.1.1\0"
#endif
#define  THINBASIC_OS_INTERNALNAME             "thinBasic_OS\0"
#define  THINBASIC_OS_FILEDESCRIPTION          "thinBasic Operating System Library\0"
#define  THINBASIC_OS_ORIGINALFILENAME         "thinBasic_OS.dll\0"
#define  THINBASIC_OS_PRODUCTNAME              "thinBasic Operating System\0"

/* THINBASIC_OS9x.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_OS9x_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_OS9x_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_OS9x_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_OS9x_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_OS9x_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_OS9x_VERSIONMAJOR             1
#define  THINBASIC_OS9x_VERSIONMINOR             0
#define  THINBASIC_OS9x_VERSIONBUILD             1
#define  THINBASIC_OS9x_VERSIONREVISION              1
#define  THINBASIC_OS9x_VERSIONLITERAL               "1.0.1.1\0"
#endif
#define  THINBASIC_OS9x_INTERNALNAME             "thinBasic_OS\0"
#define  THINBASIC_OS9x_FILEDESCRIPTION          "thinBasic Operating System Library for Windows 95/98/ME\0"
#define  THINBASIC_OS9x_ORIGINALFILENAME         "thinBasic_OS.dll\0"
#define  THINBASIC_OS9x_PRODUCTNAME              "thinBasic Operating System for Windows 95/98/ME\0"

/* THINBASIC_PC.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_PC_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_PC_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_PC_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_PC_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_PC_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_PC_VERSIONMAJOR             1
#define  THINBASIC_PC_VERSIONMINOR                 0
#define  THINBASIC_PC_VERSIONBUILD                 1
#define  THINBASIC_PC_VERSIONREVISION              1
#define  THINBASIC_PC_VERSIONLITERAL               "1.0.1.1\0"
#endif
#define  THINBASIC_PC_INTERNALNAME             "thinBasic_PC\0"
#define  THINBASIC_PC_FILEDESCRIPTION          "thinBasic Personal Computer Management Library\0"
#define  THINBASIC_PC_ORIGINALFILENAME         "thinBasic_PC.dll\0"
#define  THINBASIC_PC_PRODUCTNAME              "thinBasic Personal Computer Management\0"

/* THINBASIC_PC9x.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_PC9x_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_PC9x_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_PC9x_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_PC9x_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_PC9x_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_PC9x_VERSIONMAJOR             1
#define  THINBASIC_PC9x_VERSIONMINOR             0
#define  THINBASIC_PC9x_VERSIONBUILD             1
#define  THINBASIC_PC9x_VERSIONREVISION          1
#define  THINBASIC_PC9x_VERSIONLITERAL           "1.0.1.1\0"
#endif
#define  THINBASIC_PC9x_INTERNALNAME             "thinBasic_PC9x\0"
#define  THINBASIC_PC9x_FILEDESCRIPTION      "thinBasic Personal Computer Management Library for Windows 95/98/ME\0"
#define  THINBASIC_PC9x_ORIGINALFILENAME         "thinBasic_PC9x.dll\0"
#define  THINBASIC_PC9x_PRODUCTNAME              "thinBasic Personal Computer Management for Windows 95/98/ME\0"

/* THINBASIC_PDF.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_PDF_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_PDF_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_PDF_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_PDF_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_PDF_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_PDF_VERSIONMAJOR             1
#define  THINBASIC_PDF_VERSIONMINOR             0
#define  THINBASIC_PDF_VERSIONBUILD         1
#define  THINBASIC_PDF_VERSIONREVISION      1
#define  THINBASIC_PDF_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_PDF_INTERNALNAME             "thinBasic_PDF\0"
#define  THINBASIC_PDF_FILEDESCRIPTION              "thinBasic Portable Document Format Library\0"
#define  THINBASIC_PDF_ORIGINALFILENAME         "thinBasic_PDF.dll\0"
#define  THINBASIC_PDF_PRODUCTNAME              "thinBasic Portable Document Format\0"

/* THINBASIC_RAS.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_RAS_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_RAS_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_RAS_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_RAS_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_RAS_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_RAS_VERSIONMAJOR             1
#define  THINBASIC_RAS_VERSIONMINOR         0
#define  THINBASIC_RAS_VERSIONBUILD         1
#define  THINBASIC_RAS_VERSIONREVISION      1
#define  THINBASIC_RAS_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_RAS_INTERNALNAME             "thinBasic_RAS\0"
#define  THINBASIC_RAS_FILEDESCRIPTION              "thinBasic Remote Acces System Library\0"
#define  THINBASIC_RAS_ORIGINALFILENAME         "thinBasic_RAS.dll\0"
#define  THINBASIC_RAS_PRODUCTNAME              "thinBasic Remote Acces System\0"

/* THINBASIC_REGISTRY.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_REGISTRY_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_REGISTRY_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_REGISTRY_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_REGISTRY_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_REGISTRY_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_REGISTRY_VERSIONMAJOR        1
#define  THINBASIC_REGISTRY_VERSIONMINOR        0
#define  THINBASIC_REGISTRY_VERSIONBUILD        1
#define  THINBASIC_REGISTRY_VERSIONREVISION     1
#define  THINBASIC_REGISTRY_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_REGISTRY_INTERNALNAME    "thinBasic_REGISTRY\0"
#define  THINBASIC_REGISTRY_FILEDESCRIPTION     "thinBasic Registry Management Library\0"
#define  THINBASIC_REGISTRY_ORIGINALFILENAME    "thinBasic_REGISTRY.dll\0"
#define  THINBASIC_REGISTRY_PRODUCTNAME         "thinBasic Registry Management\0"

/* THINBASIC_SAPI.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_SAPI_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_SAPI_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_SAPI_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_SAPI_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_SAPI_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_SAPI_VERSIONMAJOR             1
#define  THINBASIC_SAPI_VERSIONMINOR                0
#define  THINBASIC_SAPI_VERSIONBUILD        1
#define  THINBASIC_SAPI_VERSIONREVISION     1
#define  THINBASIC_SAPI_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_SAPI_INTERNALNAME            "thinBasic_SAPI\0"
#define  THINBASIC_SAPI_FILEDESCRIPTION         "thinBasic SAPI File Library\0"
#define  THINBASIC_SAPI_ORIGINALFILENAME        "thinBasic_SAPI.dll\0"
#define  THINBASIC_SAPI_PRODUCTNAME             "thinBasic SAPI File\0"

/* THINBASIC_SMTP.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_SMTP_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_SMTP_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_SMTP_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_SMTP_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_SMTP_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_SMTP_VERSIONMAJOR            1
#define  THINBASIC_SMTP_VERSIONMINOR        0
#define  THINBASIC_SMTP_VERSIONBUILD        1
#define  THINBASIC_SMTP_VERSIONREVISION     1
#define  THINBASIC_SMTP_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_SMTP_INTERNALNAME            "thinBasic_SMTP\0"
#define  THINBASIC_SMTP_FILEDESCRIPTION         "thinBasic Simple Mail Transfer Protocol Library\0"
#define  THINBASIC_SMTP_ORIGINALFILENAME        "thinBasic_SMTP.dll\0"
#define  THINBASIC_SMTP_PRODUCTNAME             "thinBasic Simple Mail Transfer Protocol\0"

/* THINBASIC_UIMCTRL.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_UIMCTRL_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_UIMCTRL_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_UIMCTRL_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_UIMCTRL_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_UIMCTRL_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_UIMCTRL_VERSIONMAJOR            1
#define  THINBASIC_UIMCTRL_VERSIONMINOR        0
#define  THINBASIC_UIMCTRL_VERSIONBUILD        1
#define  THINBASIC_UIMCTRL_VERSIONREVISION     1
#define  THINBASIC_UIMCTRL_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_UIMCTRL_INTERNALNAME            "thinBasic_UIMCTRL\0"
#define  THINBASIC_UIMCTRL_FILEDESCRIPTION         "thinBasic mCtrl\0"
#define  THINBASIC_UIMCTRL_ORIGINALFILENAME        "thinBasic_UIMCTRL.dll\0"
#define  THINBASIC_UIMCTRL_PRODUCTNAME             "thinBasic mCtrl\0"

/* THINBASIC_SQL.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_SQL_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_SQL_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_SQL_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_SQL_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_SQL_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_SQL_VERSIONMAJOR             1
#define  THINBASIC_SQL_VERSIONMINOR         0
#define  THINBASIC_SQL_VERSIONBUILD         1
#define  THINBASIC_SQL_VERSIONREVISION      1
#define  THINBASIC_SQL_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_SQL_INTERNALNAME             "thinBasic_SQL\0"
#define  THINBASIC_SQL_FILEDESCRIPTION              "thinBasic Structured Query Language Library\0"
#define  THINBASIC_SQL_ORIGINALFILENAME         "thinBasic_SQL.dll\0"
#define  THINBASIC_SQL_PRODUCTNAME              "thinBasic Structured Query Language\0"

/* THINBASIC_STAT.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_STAT_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_STAT_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_STAT_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_STAT_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_STAT_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_STAT_VERSIONMAJOR            1
#define  THINBASIC_STAT_VERSIONMINOR        0
#define  THINBASIC_STAT_VERSIONBUILD        1
#define  THINBASIC_STAT_VERSIONREVISION     1
#define  THINBASIC_STAT_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_STAT_INTERNALNAME            "thinBasic_STAT\0"
#define  THINBASIC_STAT_FILEDESCRIPTION         "thinBasic Statistical Module Library\0"
#define  THINBASIC_STAT_ORIGINALFILENAME        "thinBasic_STAT.dll\0"
#define  THINBASIC_STAT_PRODUCTNAME             "thinBasic Statistical Module Library\0"

/* THINBASIC_TBASS.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_TBASS_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_TBASS_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_TBASS_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_TBASS_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_TBASS_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_TBASS_VERSIONMAJOR             1
#define  THINBASIC_TBASS_VERSIONMINOR               0
#define  THINBASIC_TBASS_VERSIONBUILD       1
#define  THINBASIC_TBASS_VERSIONREVISION    1
#define  THINBASIC_TBASS_VERSIONLITERAL     "1.0.1.1\0"
#endif
#define  THINBASIC_TBASS_INTERNALNAME               "thinBasic_TBASS\0"
#define  THINBASIC_TBASS_FILEDESCRIPTION            "thinBasic TBASS Library\0"
#define  THINBASIC_TBASS_ORIGINALFILENAME         "thinBasic_TBASS.dll\0"
#define  THINBASIC_TBASS_PRODUCTNAME              "thinBasic TBASS\0"

/* THINBASIC_TCPUDP.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_TCPUDP_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_TCPUDP_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_TCPUDP_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_TCPUDP_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_TCPUDP_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_TCPUDP_VERSIONMAJOR          1
#define  THINBASIC_TCPUDP_VERSIONMINOR          0
#define  THINBASIC_TCPUDP_VERSIONBUILD          1
#define  THINBASIC_TCPUDP_VERSIONREVISION       1
#define  THINBASIC_TCPUDP_VERSIONLITERAL        "1.0.1.1\0"
#endif
#define  THINBASIC_TCPUDP_INTERNALNAME         "thinBasic_TCPUDP\0"
#define  THINBASIC_TCPUDP_FILEDESCRIPTION      "thinBasic Transmission Control Protocol and User Datagram Protocol Library\0"
#define  THINBASIC_TCPUDP_ORIGINALFILENAME         "thinBasic_TCPUDP.dll\0"
#define  THINBASIC_TCPUDP_PRODUCTNAME              "thinBasic Transmission Control Protocol and User Datagram Protocol\0"

/* THINBASIC_TIMAGE.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_TIMAGE_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_TIMAGE_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_TIMAGE_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_TIMAGE_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_TIMAGE_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_TIMAGE_VERSIONMAJOR             1
#define  THINBASIC_TIMAGE_VERSIONMINOR               0
#define  THINBASIC_TIMAGE_VERSIONBUILD       1
#define  THINBASIC_TIMAGE_VERSIONREVISION    1
#define  THINBASIC_TIMAGE_VERSIONLITERAL     "1.0.1.1\0"
#endif
#define  THINBASIC_TIMAGE_INTERNALNAME               "thinBasic_TIMAGE\0"
#define  THINBASIC_TIMAGE_FILEDESCRIPTION            "thinBasic TIMAGE Library based on PBIMAGE.DLL By Dean Hodgson\0"
#define  THINBASIC_TIMAGE_ORIGINALFILENAME         "thinBasic_TIMAGE.dll\0"
#define  THINBASIC_TIMAGE_PRODUCTNAME              "thinBasic TBASS\0"


/* THINBASIC_TOKENIZER.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_TOKENIZER_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_TOKENIZER_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_TOKENIZER_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_TOKENIZER_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_TOKENIZER_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_TOKENIZER_VERSIONMAJOR             1
#define  THINBASIC_TOKENIZER_VERSIONMINOR               0
#define  THINBASIC_TOKENIZER_VERSIONBUILD       1
#define  THINBASIC_TOKENIZER_VERSIONREVISION    1
#define  THINBASIC_TOKENIZER_VERSIONLITERAL     "1.0.1.1\0"
#endif
#define  THINBASIC_TOKENIZER_INTERNALNAME               "thinBasic_Tokenizer\0"
#define  THINBASIC_TOKENIZER_FILEDESCRIPTION            "thinBasic Tokenizer Library\0"
#define  THINBASIC_TOKENIZER_ORIGINALFILENAME         "thinBasic_Tokenizer.dll\0"
#define  THINBASIC_TOKENIZER_PRODUCTNAME              "thinBasic Tokenizer\0"

/* THINBASIC_TRACE.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_TRACE_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_TRACE_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_TRACE_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_TRACE_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_TRACE_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_TRACE_VERSIONMAJOR             1
#define  THINBASIC_TRACE_VERSIONMINOR         0
#define  THINBASIC_TRACE_VERSIONBUILD         1
#define  THINBASIC_TRACE_VERSIONREVISION      1
#define  THINBASIC_TRACE_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_TRACE_INTERNALNAME             "thinBasic_TRACE\0"
#define  THINBASIC_TRACE_FILEDESCRIPTION      "thinBasic TRACE Library\0"
#define  THINBASIC_TRACE_ORIGINALFILENAME         "thinBasic_TRACE.dll\0"
#define  THINBASIC_TRACE_PRODUCTNAME              "thinBasic TRACE\0"


/* THINBASIC_UI.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_UI_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_UI_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_UI_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_UI_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_UI_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_UI_VERSIONMAJOR             1
#define  THINBASIC_UI_VERSIONMINOR          0
#define  THINBASIC_UI_VERSIONBUILD          1
#define  THINBASIC_UI_VERSIONREVISION       1
#define  THINBASIC_UI_VERSIONLITERAL        "1.0.1.1\0"
#endif
#define  THINBASIC_UI_INTERNALNAME             "thinBasic_UI\0"
#define  THINBASIC_UI_FILEDESCRIPTION          "thinBasic User Interface Library\0"
#define  THINBASIC_UI_ORIGINALFILENAME         "thinBasic_UI.dll\0"
#define  THINBASIC_UI_PRODUCTNAME              "thinBasic User Interface\0"

/* THINBASIC_UI_UIAdv.Dll */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_UIAdv_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_UIAdv_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_UIAdv_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_UIAdv_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_UIAdv_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_UIAdv_VERSIONMAJOR             1
#define  THINBASIC_UIAdv_VERSIONMINOR          0
#define  THINBASIC_UIAdv_VERSIONBUILD          1
#define  THINBASIC_UIAdv_VERSIONREVISION       1
#define  THINBASIC_UIAdv_VERSIONLITERAL        "1.0.1.1\0"
#endif
#define  THINBASIC_UIAdv_INTERNALNAME             "thinBasic_UI_UIAdv\0"
#define  THINBASIC_UIAdv_FILEDESCRIPTION          "thinBasic Advanced User Interface controls\0"
#define  THINBASIC_UIAdv_ORIGINALFILENAME         "thinBasic_UI_UIAdv.dll\0"
#define  THINBASIC_UIAdv_PRODUCTNAME              "thinBasic Advanced User Interface controls\0"

/* THINBASIC_WEBBROWSER.Dll */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_WEBBROWSER_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_WEBBROWSER_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_WEBBROWSER_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_WEBBROWSER_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_WEBBROWSER_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_WEBBROWSER_VERSIONMAJOR             1
#define  THINBASIC_WEBBROWSER_VERSIONMINOR          0
#define  THINBASIC_WEBBROWSER_VERSIONBUILD          1
#define  THINBASIC_WEBBROWSER_VERSIONREVISION       1
#define  THINBASIC_WEBBROWSER_VERSIONLITERAL        "1.0.1.1\0"
#endif
#define  THINBASIC_WEBBROWSER_INTERNALNAME             "thinBasic_WebBrowser\0"
#define  THINBASIC_WEBBROWSER_FILEDESCRIPTION          "thinBasic WebBrowser control\0"
#define  THINBASIC_WEBBROWSER_ORIGINALFILENAME         "thinBasic_WebBrowser.dll\0"
#define  THINBASIC_WEBBROWSER_PRODUCTNAME              "thinBasic WebBrowser control\0"

/* THINBASIC_UI_PROPLIST.Dll */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_UI_PROPLIST_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_UI_PROPLIST_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_UI_PROPLIST_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_UI_PROPLIST_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_UI_PROPLIST_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_UI_PROPLIST_VERSIONMAJOR             1
#define  THINBASIC_UI_PROPLIST_VERSIONMINOR          0
#define  THINBASIC_UI_PROPLIST_VERSIONBUILD          1
#define  THINBASIC_UI_PROPLIST_VERSIONREVISION       1
#define  THINBASIC_UI_PROPLIST_VERSIONLITERAL        "1.0.1.1\0"
#endif
#define  THINBASIC_UI_PROPLIST_INTERNALNAME             "thinBasic_UI_PROPLIST\0"
#define  THINBASIC_UI_PROPLIST_FILEDESCRIPTION          "thinBasic User Interface Property List control\0"
#define  THINBASIC_UI_PROPLIST_ORIGINALFILENAME         "thinBasic_UI_PROPLIST.dll\0"
#define  THINBASIC_UI_PROPLIST_PRODUCTNAME              "thinBasic User Interface Property List control\0"

/* THINBASIC_VBREGEXP.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_VBREGEXP_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_VBREGEXP_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_VBREGEXP_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_VBREGEXP_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_VBREGEXP_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_VBREGEXP_VERSIONMAJOR             1
#define  THINBASIC_VBREGEXP_VERSIONMINOR                0
#define  THINBASIC_VBREGEXP_VERSIONBUILD        1
#define  THINBASIC_VBREGEXP_VERSIONREVISION     1
#define  THINBASIC_VBREGEXP_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_VBREGEXP_INTERNALNAME            "thinBasic_VBREGEXP\0"
#define  THINBASIC_VBREGEXP_FILEDESCRIPTION             "thinBasic VB Regular Expression wrap Library\0"
#define  THINBASIC_VBREGEXP_ORIGINALFILENAME         "thinBasic_VBREGEXP.dll\0"
#define  THINBASIC_VBREGEXP_PRODUCTNAME              "thinBasic VBREGEXP File\0"

/* THINBASIC_WINUTILS.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_WINUTILS_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_WINUTILS_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_WINUTILS_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_WINUTILS_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_WINUTILS_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_WINUTILS_VERSIONMAJOR        1
#define  THINBASIC_WINUTILS_VERSIONMINOR        0
#define  THINBASIC_WINUTILS_VERSIONBUILD        1
#define  THINBASIC_WINUTILS_VERSIONREVISION     1
#define  THINBASIC_WINUTILS_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_WINUTILS_INTERNALNAME    "thinBasic_WINUTILS\0"
#define  THINBASIC_WINUTILS_FILEDESCRIPTION     "thinBasic Windows Utilities Library\0"
#define  THINBASIC_WINUTILS_ORIGINALFILENAME    "thinBasic_WINUTILS.dll\0"
#define  THINBASIC_WINUTILS_PRODUCTNAME         "thinBasic Windows Utilities\0"

/* THINBASIC_WMI.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_WMI_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_WMI_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_WMI_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_WMI_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_WMI_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_WMI_VERSIONMAJOR             1
#define  THINBASIC_WMI_VERSIONMINOR               0
#define  THINBASIC_WMI_VERSIONBUILD       1
#define  THINBASIC_WMI_VERSIONREVISION    1
#define  THINBASIC_WMI_VERSIONLITERAL     "1.0.1.1\0"
#endif
#define  THINBASIC_WMI_INTERNALNAME               "thinBasic_WMI\0"
#define  THINBASIC_WMI_FILEDESCRIPTION            "thinBasic WMI Library\0"
#define  THINBASIC_WMI_ORIGINALFILENAME         "thinBasic_WMI.dll\0"
#define  THINBASIC_WMI_PRODUCTNAME              "thinBasic WMI\0"


/* THINBASIC_XML.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_XML_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_XML_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_XML_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_XML_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_XML_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_XML_VERSIONMAJOR             1
#define  THINBASIC_XML_VERSIONMINOR         0
#define  THINBASIC_XML_VERSIONBUILD         1
#define  THINBASIC_XML_VERSIONREVISION      1
#define  THINBASIC_XML_VERSIONLITERAL       "1.0.1.1\0"
#endif
#define  THINBASIC_XML_INTERNALNAME             "thinBasic_XML\0"
#define  THINBASIC_XML_FILEDESCRIPTION              "thinBasic Extensible Markup Language Library\0"
#define  THINBASIC_XML_ORIGINALFILENAME         "thinBasic_XML.dll\0"
#define  THINBASIC_XML_PRODUCTNAME              "thinBasic Extensible Markup Language\0"

/* THINBASIC_XPRINT.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_XPRINT_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_XPRINT_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_XPRINT_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_XPRINT_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_XPRINT_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_XPRINT_VERSIONMAJOR             1
#define  THINBASIC_XPRINT_VERSIONMINOR          0
#define  THINBASIC_XPRINT_VERSIONBUILD          1
#define  THINBASIC_XPRINT_VERSIONREVISION       1
#define  THINBASIC_XPRINT_VERSIONLITERAL        "1.0.1.1\0"
#endif
#define  THINBASIC_XPRINT_INTERNALNAME              "thinBasic_XPRINT\0"
#define  THINBASIC_XPRINT_FILEDESCRIPTION           "thinBasic Extended Printing Library\0"
#define  THINBASIC_XPRINT_ORIGINALFILENAME         "thinBasic_XPRINT.dll\0"
#define  THINBASIC_XPRINT_PRODUCTNAME              "thinBasic Extended Printing Library\0"

/* THINBASIC_ZLIB.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_ZLIB_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_ZLIB_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_ZLIB_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_ZLIB_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_ZLIB_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_ZLIB_VERSIONMAJOR             1
#define  THINBASIC_ZLIB_VERSIONMINOR         0
#define  THINBASIC_ZLIB_VERSIONBUILD         1
#define  THINBASIC_ZLIB_VERSIONREVISION      1
#define  THINBASIC_ZLIB_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_ZLIB_INTERNALNAME             "thinBasic_ZLIB\0"
#define  THINBASIC_ZLIB_FILEDESCRIPTION      "thinBasic ZLIB Library\0"
#define  THINBASIC_ZLIB_ORIGINALFILENAME         "thinBasic_ZLIB.dll\0"
#define  THINBASIC_ZLIB_PRODUCTNAME              "thinBasic ZLIB\0"


/* THINRES.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINRES_VERSIONMAJOR              THIN_VERSIONMAJOR
#define  THINRES_VERSIONMINOR              THIN_VERSIONMINOR
#define  THINRES_VERSIONBUILD              THIN_VERSIONBUILD
#define  THINRES_VERSIONREVISION           THIN_VERSIONREVISION
#define  THINRES_VERSIONLITERAL            THIN_VERSIONLITERAL
#else
#define  THINRES_VERSIONMAJOR              1
#define  THINRES_VERSIONMINOR              0
#define  THINRES_VERSIONBUILD              1
#define  THINRES_VERSIONREVISION           1
#define  THINRES_VERSIONLITERAL            "1.0.1.1\0"
#endif
#define  THINRES_INTERNALNAME              "ThinRes\0"
#define  THINRES_FILEDESCRIPTION           "thinBasic Resources Library\0"
#define  THINRES_ORIGINALFILENAME          "ThinRes.dll\0"
#define  THINRES_PRODUCTNAME               "thinBasic Resources\0"

/* THINRTE.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINRTE_VERSIONMAJOR              THIN_VERSIONMAJOR
#define  THINRTE_VERSIONMINOR              THIN_VERSIONMINOR
#define  THINRTE_VERSIONBUILD              THIN_VERSIONBUILD
#define  THINRTE_VERSIONREVISION           THIN_VERSIONREVISION
#define  THINRTE_VERSIONLITERAL            THIN_VERSIONLITERAL
#else
#define  THINRTE_VERSIONMAJOR              1
#define  THINRTE_VERSIONMINOR              0
#define  THINRTE_VERSIONBUILD              1
#define  THINRTE_VERSIONREVISION           1
#define  THINRTE_VERSIONLITERAL            "1.0.1.1\0"
#endif
#define  THINRTE_INTERNALNAME              "ThinRTE\0"
#define  THINRTE_FILEDESCRIPTION           "thinBasic Run-Time Error Handling Library\0"
#define  THINRTE_ORIGINALFILENAME          "ThinRTE.dll\0"
#define  THINRTE_PRODUCTNAME               "thinBasic Run-Time Error Handling\0"

/* THINVL.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINVL_VERSIONMAJOR              THIN_VERSIONMAJOR
#define  THINVL_VERSIONMINOR              THIN_VERSIONMINOR
#define  THINVL_VERSIONBUILD              THIN_VERSIONBUILD
#define  THINVL_VERSIONREVISION           THIN_VERSIONREVISION
#define  THINVL_VERSIONLITERAL            THIN_VERSIONLITERAL
#else
#define  THINVL_VERSIONMAJOR              1
#define  THINVL_VERSIONMINOR              0
#define  THINVL_VERSIONBUILD              1
#define  THINVL_VERSIONREVISION           1
#define  THINVL_VERSIONLITERAL            "1.0.1.1\0"
#endif
#define  THINVL_INTERNALNAME              "thinVL\0"
#define  THINVL_FILEDESCRIPTION           "thinBasic Validation Layer Library\0"
#define  THINVL_ORIGINALFILENAME          "thinVL.dll\0"
#define  THINVL_PRODUCTNAME               "thinBasic Validation Layer\0"

/* THINCORE.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINCORE_VERSIONMAJOR              THIN_VERSIONMAJOR
#define  THINCORE_VERSIONMINOR              THIN_VERSIONMINOR
#define  THINCORE_VERSIONBUILD              THIN_VERSIONBUILD
#define  THINCORE_VERSIONREVISION           THIN_VERSIONREVISION
#define  THINCORE_VERSIONLITERAL            THIN_VERSIONLITERAL
#else
#define  THINCORE_VERSIONMAJOR              1
#define  THINCORE_VERSIONMINOR              0
#define  THINCORE_VERSIONBUILD              1
#define  THINCORE_VERSIONREVISION           1
#define  THINCORE_VERSIONLITERAL            "1.0.1.1\0"
#endif
#define  THINCORE_INTERNALNAME              "thinCore\0"
#define  THINCORE_FILEDESCRIPTION           "thinBasic Core Engine\0"
#define  THINCORE_ORIGINALFILENAME          "thinCore.dll\0"
#define  THINCORE_PRODUCTNAME               "thinBasic Core Engine\0"

/* THINDICT.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINDICT_VERSIONMAJOR              THIN_VERSIONMAJOR
#define  THINDICT_VERSIONMINOR              THIN_VERSIONMINOR
#define  THINDICT_VERSIONBUILD              THIN_VERSIONBUILD
#define  THINDICT_VERSIONREVISION           THIN_VERSIONREVISION
#define  THINDICT_VERSIONLITERAL            THIN_VERSIONLITERAL
#else
#define  THINDICT_VERSIONMAJOR              1
#define  THINDICT_VERSIONMINOR              0
#define  THINDICT_VERSIONBUILD              1
#define  THINDICT_VERSIONREVISION           1
#define  THINDICT_VERSIONLITERAL            "1.0.1.1\0"
#endif
#define  THINDICT_INTERNALNAME              "THINDICT\0"
#define  THINDICT_FILEDESCRIPTION           "thinBasic Dictionary Library\0"
#define  THINDICT_ORIGINALFILENAME          "THINDICT.dll\0"
#define  THINDICT_PRODUCTNAME               "thinBasic Dictionary\0"

/* KEYACT.EXE */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  KEYACT_VERSIONMAJOR                THIN_VERSIONMAJOR
#define  KEYACT_VERSIONMINOR                THIN_VERSIONMINOR
#define  KEYACT_VERSIONBUILD                THIN_VERSIONBUILD
#define  KEYACT_VERSIONREVISION             THIN_VERSIONREVISION
#define  KEYACT_VERSIONLITERAL              THIN_VERSIONLITERAL
#else
#define  KEYACT_VERSIONMAJOR                1
#define  KEYACT_VERSIONMINOR                0
#define  KEYACT_VERSIONBUILD                1
#define  KEYACT_VERSIONREVISION             1
#define  KEYACT_VERSIONLITERAL              "1.0.1.1\0"
#endif
#define  KEYACT_INTERNALNAME                "KeyAct\0"
#define  KEYACT_FILEDESCRIPTION             "thinBasic Key Activactor Application\0"
#define  KEYACT_ORIGINALFILENAME            "KeyAct.exe\0"
#define  KEYACT_PRODUCTNAME                 "thinBasic Key Activactor\0"

/* THINBASIC.EXE */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_VERSIONMAJOR                THIN_VERSIONMAJOR
#define  THINBASIC_VERSIONMINOR                THIN_VERSIONMINOR
#define  THINBASIC_VERSIONBUILD                THIN_VERSIONBUILD
#define  THINBASIC_VERSIONREVISION             THIN_VERSIONREVISION
#define  THINBASIC_VERSIONLITERAL              THIN_VERSIONLITERAL
#else
#define  THINBASIC_VERSIONMAJOR                1
#define  THINBASIC_VERSIONMINOR                0
#define  THINBASIC_VERSIONBUILD                1
#define  THINBASIC_VERSIONREVISION             1
#define  THINBASIC_VERSIONLITERAL              "1.0.1.1\0"
#endif
#define  THINBASIC_INTERNALNAME                "thinBasic\0"
#define  THINBASIC_FILEDESCRIPTION             "thinBasic Programming Language GUI version\0"
#define  THINBASIC_ORIGINALFILENAME            "thinBasic.exe\0"
#define  THINBASIC_PRODUCTNAME                 "thinBasic Programming Language GUI version\0"

/* THINBASICC.EXE */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASICC_VERSIONMAJOR                THIN_VERSIONMAJOR
#define  THINBASlCC_VERSIONMINOR                THIN_VERSIONMINOR
#define  THINBASICC_VERSIONBUILD                THIN_VERSIONBUILD
#define  THINBASICC_VERSIONREVISION             THIN_VERSIONREVISION
#define  THINBASICC_VERSIONLITERAL              THIN_VERSIONLITERAL
#else
#define  THINBASICC_VERSIONMAJOR                1
#define  THINBASICC_VERSIONMINOR                0
#define  THINBASICC_VERSIONBUILD                1
#define  THINBASICC_VERSIONREVISION             1
#define  THINBASICC_VERSIONLITERAL              "1.0.1.1\0"
#endif
#define  THINBASICC_INTERNALNAME                "thinBasicC\0"
#define  THINBASICC_FILEDESCRIPTION             "thinBasic Programming Language Console version\0"
#define  THINBASICC_ORIGINALFILENAME            "thinBasicC.exe\0"
#define  THINBASICC_PRODUCTNAME                 "thinBasic Programming Language Console version\0"

/* THINAIR.EXE */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_THINAIR_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_THINAIR_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_THINAIR_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_THINAIR_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_THINAIR_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_THINAIR_VERSIONMAJOR        1
#define  THINBASIC_THINAIR_VERSIONMINOR        0
#define  THINBASIC_THINAIR_VERSIONBUILD        1
#define  THINBASIC_THINAIR_VERSIONREVISION     1
#define  THINBASIC_THINAIR_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_THINAIR_INTERNALNAME        "thinAir\0"
#define  THINBASIC_THINAIR_FILEDESCRIPTION     "thinAir: IDE and debugger for thinBasic Programming Language\0"
#define  THINBASIC_THINAIR_ORIGINALFILENAME    "thinAir.exe\0"
#define  THINBASIC_THINAIR_PRODUCTNAME         "thinAir: IDE and debugger for thinBasic Programming Language\0"

/* THINAIR9x.EXE */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_THINAIR9x_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_THINAIR9x_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_THINAIR9x_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_THINAIR9x_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_THINAIR9x_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_THINAIR9x_VERSIONMAJOR        1
#define  THINBASIC_THINAIR9x_VERSIONMINOR        0
#define  THINBASIC_THINAIR9x_VERSIONBUILD        1
#define  THINBASIC_THINAIR9x_VERSIONREVISION     1
#define  THINBASIC_THINAIR9x_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_THINAIR9x_INTERNALNAME        "Thin Air\0"
#define  THINBASIC_THINAIR9x_FILEDESCRIPTION     "Thin Air IDE and debugger application for Windows 95/98/ME\0"
#define  THINBASIC_THINAIR9x_ORIGINALFILENAME    "ThinAir.exe\0"
#define  THINBASIC_THINAIR9x_PRODUCTNAME         "Thin Air IDE and debugger for Windows 95/98/ME\0"

/* THINAIRC.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_THINAIRCDLL_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_THINAIRCDLL_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_THINAIRCDLL_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_THINAIRCDLL_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_THINAIRCDLL_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_THINAIRCDLL_VERSIONMAJOR        1
#define  THINBASIC_THINAIRCDLL_VERSIONMINOR        0
#define  THINBASIC_THINAIRCDLL_VERSIONBUILD        1
#define  THINBASIC_THINAIRCDLL_VERSIONREVISION     1
#define  THINBASIC_THINAIRCDLL_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_THINAIRCDLL_INTERNALNAME        "Thin Air\0"
#define  THINBASIC_THINAIRCDLL_FILEDESCRIPTION     "Thin Air IDE C Support Module\0"
#define  THINBASIC_THINAIRCDLL_ORIGINALFILENAME    "ThinAir.dll\0"
#define  THINBASIC_THINAIRCDLL_PRODUCTNAME         "Thin Air C Support Module\0"

/* THINAIRB.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_THINAIRBDLL_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_THINAIRBDLL_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_THINAIRBDLL_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_THINAIRBDLL_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_THINAIRBDLL_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_THINAIRBDLL_VERSIONMAJOR        1
#define  THINBASIC_THINAIRBDLL_VERSIONMINOR        0
#define  THINBASIC_THINAIRBDLL_VERSIONBUILD        1
#define  THINBASIC_THINAIRBDLL_VERSIONREVISION     1
#define  THINBASIC_THINAIRBDLL_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_THINAIRBDLL_INTERNALNAME        "Thin Air\0"
#define  THINBASIC_THINAIRBDLL_FILEDESCRIPTION     "Thin Air IDE B Support Module\0"
#define  THINBASIC_THINAIRBDLL_ORIGINALFILENAME    "ThinAir.dll\0"
#define  THINBASIC_THINAIRBDLL_PRODUCTNAME         "Thin Air B Support Module\0"

/* THINBASIC_EXE.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_EXE_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_EXE_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_EXE_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_EXE_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_EXE_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_EXE_VERSIONMAJOR        1
#define  THINBASIC_EXE_VERSIONMINOR        0
#define  THINBASIC_EXE_VERSIONBUILD        1
#define  THINBASIC_EXE_VERSIONREVISION     1
#define  THINBASIC_EXE_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_EXE_INTERNALNAME        "thinBasic Exe\0"
#define  THINBASIC_EXE_FILEDESCRIPTION     "ThinBasic Executables' files support\0"
#define  THINBASIC_EXE_ORIGINALFILENAME    "ThinBasic_Exe.dll\0"
#define  THINBASIC_EXE_PRODUCTNAME         "ThinBasic Exe\0"

/* THINBASIC_BUNDLE.EXE */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_BUNDLE_EXE_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_BUNDLE_EXE_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_BUNDLE_EXE_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_BUNDLE_EXE_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_BUNDLE_EXE_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_BUNDLE_EXE_VERSIONMAJOR        1
#define  THINBASIC_BUNDLE_EXE_VERSIONMINOR        0
#define  THINBASIC_BUNDLE_EXE_VERSIONBUILD        1
#define  THINBASIC_BUNDLE_EXE_VERSIONREVISION     1
#define  THINBASIC_BUNDLE_EXE_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_BUNDLE_EXE_INTERNALNAME        "thinBasic Bundle\0"
#define  THINBASIC_BUNDLE_EXE_FILEDESCRIPTION     "ThinBasic Bundle Stub Executable\0"
#define  THINBASIC_BUNDLE_EXE_ORIGINALFILENAME    "ThinBasic_Bundle.exe\0"
#define  THINBASIC_BUNDLE_EXE_PRODUCTNAME         "ThinBasic Bundle Stub\0"

/* THINBASIC_LAN.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_LAN_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_LAN_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_LAN_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_LAN_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_LAN_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_LAN_VERSIONMAJOR             1
#define  THINBASIC_LAN_VERSIONMINOR             0
#define  THINBASIC_LAN_VERSIONBUILD             1
#define  THINBASIC_LAN_VERSIONREVISION              1
#define  THINBASIC_LAN_VERSIONLITERAL               "1.0.1.1\0"
#endif
#define  THINBASIC_LAN_INTERNALNAME             "thinBasic_LAN\0"
#define  THINBASIC_LAN_FILEDESCRIPTION          "thinBasic Network Management Library\0"
#define  THINBASIC_LAN_ORIGINALFILENAME         "thinBasic_LAN.dll\0"
#define  THINBASIC_LAN_PRODUCTNAME              "thinBasic Network Management\0"

/* THINBASIC_LAN9x.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_LAN9x_VERSIONMAJOR             THIN_VERSIONMAJOR
#define  THINBASIC_LAN9x_VERSIONMINOR             THIN_VERSIONMINOR
#define  THINBASIC_LAN9x_VERSIONBUILD             THIN_VERSIONBUILD
#define  THINBASIC_LAN9x_VERSIONREVISION          THIN_VERSIONREVISION
#define  THINBASIC_LAN9x_VERSIONLITERAL           THIN_VERSIONLITERAL
#else
#define  THINBASIC_LAN9x_VERSIONMAJOR             1
#define  THINBASIC_LAN9x_VERSIONMINOR             0
#define  THINBASIC_LAN9x_VERSIONBUILD             1
#define  THINBASIC_LAN9x_VERSIONREVISION              1
#define  THINBASIC_LAN9x_VERSIONLITERAL               "1.0.1.1\0"
#endif
#define  THINBASIC_LAN9x_INTERNALNAME             "thinBasic_LAN\0"
#define  THINBASIC_LAN9x_FILEDESCRIPTION          "thinBasic Network Management Library for Windows 95/98/ME\0"
#define  THINBASIC_LAN9x_ORIGINALFILENAME         "thinBasic_LAN.dll\0"
#define  THINBASIC_LAN9x_PRODUCTNAME              "thinBasic Network Management for Windows 95/98/ME\0"

/* THINBASIC_BUNDLE.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_BUNDLE_DLL_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_BUNDLE_DLL_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_BUNDLE_DLL_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_BUNDLE_DLL_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_BUNDLE_DLL_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_BUNDLE_DLL_VERSIONMAJOR        1
#define  THINBASIC_BUNDLE_DLL_VERSIONMINOR        0
#define  THINBASIC_BUNDLE_DLL_VERSIONBUILD        1
#define  THINBASIC_BUNDLE_DLL_VERSIONREVISION     1
#define  THINBASIC_BUNDLE_DLL_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_BUNDLE_DLL_INTERNALNAME        "thinBasic Bundle\0"
#define  THINBASIC_BUNDLE_DLL_FILEDESCRIPTION     "ThinBasic Bundle Support Module\0"
#define  THINBASIC_BUNDLE_DLL_ORIGINALFILENAME    "ThinBasic_Bundle.dll\0"
#define  THINBASIC_BUNDLE_DLL_PRODUCTNAME         "ThinBasic Bundle\0"

/* THINBASIC_IRRLICHT.DLL */
#ifdef FORCE_VERSION_EQUAL_FOR_ALL_MODULES
#define  THINBASIC_IRRLICHT_DLL_VERSIONMAJOR        THIN_VERSIONMAJOR
#define  THINBASIC_IRRLICHT_DLL_VERSIONMINOR        THIN_VERSIONMINOR
#define  THINBASIC_IRRLICHT_DLL_VERSIONBUILD        THIN_VERSIONBUILD
#define  THINBASIC_IRRLICHT_DLL_VERSIONREVISION     THIN_VERSIONREVISION
#define  THINBASIC_IRRLICHT_DLL_VERSIONLITERAL      THIN_VERSIONLITERAL
#else
#define  THINBASIC_IRRLICHT_DLL_VERSIONMAJOR        1
#define  THINBASIC_IRRLICHT_DLL_VERSIONMINOR        0
#define  THINBASIC_IRRLICHT_DLL_VERSIONBUILD        1
#define  THINBASIC_IRRLICHT_DLL_VERSIONREVISION     1
#define  THINBASIC_IRRLICHT_DLL_VERSIONLITERAL      "1.0.1.1\0"
#endif
#define  THINBASIC_IRRLICHT_DLL_INTERNALNAME        "thinBasic Irrlicht\0"
#define  THINBASIC_IRRLICHT_DLL_FILEDESCRIPTION     "ThinBasic Irrlicht Engine Support Module\0"
#define  THINBASIC_IRRLICHT_DLL_ORIGINALFILENAME    "ThinBasic_Irrlicht.dll\0"
#define  THINBASIC_IRRLICHT_DLL_PRODUCTNAME         "ThinBasic Irrlicht\0"
